### ISSUE TITLE
Why do I need eval if I can just run the binary itself?

### ISSUE THREAD

**Issue by melekes** [Liamsi/aliens#1]
```
eval $GOPATH/bin/aliens
```

vs

```
aliens
```

**Comment by Liamsi** [comment]
Good point! Though the `eval` version also works if `$GOPATH/bin` is not in the systems `PATH`. 

The `eval` is not needed in bash but in other shells (like [fish](https://fishshell.com/) for instance) and works in bash as well, as far as I remember. 

I could add a line that if `$GOPATH/bin` is [included](https://github.com/golang/go/wiki/GOPATH#integrating-gopath) in the systems path, one can simply run the simulation (with the provided example file and the default of 8 aliens) by running:
```
aliens
```

**Comment by melekes** [comment]
Valid points! Just not used to such syntax.

**Comment by Liamsi** [comment]
Thanks @melekes :-) 
Closing this.
